React components
frontend-course-2017/frontend-2 pull request #1
Opened 2017-05-13 17:33 UTC by frontend-course-2017

Страница списка товаров разбита на компоненты:
- не подключены шрифты
- не до конца сделана разбивка стилей
- нет детальной карточки товара
- недонастроен роутинг

2017-05-14 10:46 UTC, imevro requested changes
1) исправь еслинт
2) исправь все проверки массивов на дефолтный пустой массив
3) избавься от module.exports, что это такое вообще, у нас ес6 модули
4) пофикси сетку (поставь react-flexbox-grid)

В целом норм, но нужно чистить. Как закончишь — смерджим и перейдем к styled-components

2017-05-14 10:46 UTC, evgenyrodionov commented on src/App.js
> +import './normalize.css';
Поставь из нпма

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Products/Detail/ColorSelector/index.js
> +  if (colors.length > 0) {
```
const renderItems = (colors = []) => (
  colors.map(color => <button />)
)
```

Элегантнее и без лишних проверок!

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Products/Detail/Description/index.js
> +    <p dangerouslySetInnerHTML={{__html: text}}>
Ээээ нет

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Products/Detail/Description/index.js
> +    <p dangerouslySetInnerHTML={{__html: text}}>
danger на то и danger, тупо вставь {text} и всё

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Products/Detail/Thumbnails/index.js
> +function renderItems(srcs) {
Тоже самое

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Products/List/Items.js
> +function renderItems(items) {
Лол, можно проще — в флексбокс.цсс и реакт-флексбокс-грид можно сколько угодно колонок вкладывать в <row></row>, он норм распределит и всё будет ок

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Products/List/SaleBadge.js
> +  console.log(additionalClass);
Убирай

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Products/List/SaleBadge.js
> +function SaleBadge({ sale, additionalClass }) {
additionalClass → className

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Products/List/SaleBadge.js
> +module.exports = SaleBadge;
Чё? У нас же es6 модули

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Products/List/SaleBadge.js
> +  if (!sale) {
Вынеси отсюда 

https://facebook.github.io/react/docs/conditional-rendering.html#inline-if-with-logical--operator

2017-05-14 10:46 UTC, evgenyrodionov commented on src/Sidebar/Logo/index.js
> +    <a href="#">
У тебя же реакт-роутер

2017-05-14 18:14 UTC, frontend-course-2017 commented on src/App.js
> +import './normalize.css';
Поправил.

2017-05-14 18:14 UTC, frontend-course-2017 commented on src/Products/Detail/ColorSelector/index.js
> +  if (colors.length > 0) {
Поправил.

2017-05-14 18:14 UTC, frontend-course-2017 commented on src/Products/Detail/Description/index.js
> +    <p dangerouslySetInnerHTML={{__html: text}}>
Поправил.

2017-05-14 18:15 UTC, frontend-course-2017 commented on src/Products/Detail/Thumbnails/index.js
> +function renderItems(srcs) {
Поправил.

2017-05-14 18:15 UTC, frontend-course-2017 commented on src/Products/List/Items.js
> +function renderItems(items) {
Поправил.

2017-05-14 18:15 UTC, frontend-course-2017 commented on src/Products/List/SaleBadge.js
> +function SaleBadge({ sale, additionalClass }) {
Поправил.

2017-05-14 18:15 UTC, frontend-course-2017 commented on src/Products/List/SaleBadge.js
> +  if (!sale) {
Поправил.

2017-05-14 18:15 UTC, frontend-course-2017 commented on src/Products/List/SaleBadge.js
> +  console.log(additionalClass);
Поправил.

2017-05-14 18:15 UTC, frontend-course-2017 commented on src/Products/List/SaleBadge.js
> +module.exports = SaleBadge;
Поправил.

2017-05-14 18:16 UTC, frontend-course-2017 commented
Вроде бы все пункты исправил.

2017-05-15 09:53 UTC, imevro requested changes
1) выкинь ненужные зависимости
2) Item плохое название, оно слишком генерик, вообще непонятно к чему относится. Переименуй нормально: Card, Button, etc
3) директории ради одного файла не нужны
4) рандом в качестве ключа — нет

2017-05-15 09:53 UTC, evgenyrodionov commented on 6.0.0
> +frontend-2@0.1.0 C:\Courses\frontend 2017.05\homework\frontend-2
Это что? Убери этот файл

2017-05-15 09:53 UTC, evgenyrodionov commented on package.json
> +    "aphrodite": "^1.2.1",
Это что?

2017-05-15 09:53 UTC, evgenyrodionov commented on package.json
> +    "babel-polyfill": "^6.23.0",
Это зачем?

2017-05-15 09:53 UTC, evgenyrodionov commented on package.json
> +    "normalize-css": "^2.3.1",
Это не официальный

2017-05-15 09:53 UTC, evgenyrodionov commented on package.json
> +    "react-flexbox-grid-aphrodite": "^1.0.3",
Зачем?

2017-05-15 09:53 UTC, evgenyrodionov commented on src/App.jsx
> +require('normalize-css');
import 'normalize.css'

2017-05-15 09:53 UTC, evgenyrodionov commented on src/Products/Detail/ColorSelector/index.jsx
> +    <button key={shortid.generate()} className={`color-selector-button ${color.className}`}>
Нет

2017-05-15 09:53 UTC, evgenyrodionov commented on src/Products/List/Filters/Gender/index.jsx
> +import Item from '../Item';
Это кнопка, не айтем

2017-05-15 15:38 UTC, frontend-course-2017 commented
Поправил

2017-05-15 18:55 UTC, imevro requested changes
↓

2017-05-15 18:55 UTC, evgenyrodionov commented on src/Products/List/Filters/index.jsx
> +const genderItems = [
Не-не, не делай так. В реакте конфигурационный подход хуёвый: джсх выразительнее джсона, поэтому просто опиши в вёрстке.

2017-05-15 18:55 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +const products = [
Тут можно, если что: потому что будет приходить с сервера

2017-05-15 18:55 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
> +const menuItems = [
А тут опять нельзя

2017-05-16 09:25 UTC, imevro approved these changes

2017-05-16 09:25 UTC, evgenyrodionov commented
Фикси верстку и переводи на стайлед-компонентс

2017-05-16 09:26 UTC, merged